todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns = [
    path('create/', views.TodoCreate.as_view(), name='create'),
    path('', views.TodoList.as_view(), name='list'),
    path('completed/', views.TodoCompletedList.as_view(), name='complete_list'),
    path('<int:pk>/', views.TodoDetail.as_view(), name='detail'),
    path('<int:pk>/delete', views.TodoDelete.as_view(), name='delete'),
    path('<int:pk>/edit/', views.TodoEdit.as_view(), name='edit'),
    path('<int:pk>/complete/', views.TodoComplete.as_view(), name='complete'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import  home_view, signupuser
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/', signupuser, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('', home_view, name='home'),
    path('todo/', include('todo.urls'))
]

accounts/models.py
from django.db import models
# Create your models here.

todo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class TodoModel(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    completed = models.DateTimeField(default=None, null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo:detail", kwargs={"pk": self.pk})

accounts/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):

    fullname = forms.CharField()
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ["fullname", "email", "username", ]
        help_texts = {'username': None }

todo/forms.py
from django import forms
from .models import TodoModel

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoModel
        fields = ['title', 'memo']
    

accounts/views.py
from django.shortcuts import render, reverse
from django.views.generic import CreateView
from django.contrib.auth.models import User
from .forms import SignUpForm
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.


# class SignUpView(CreateView):
#     model = User
#     form_class = SignUpForm
#     template_name = 'accounts/registration.html'
#     success_url = 'home.html'


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'accounts/registration.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'accounts/registration.html', {'form': UserCreationForm(), 'error': 'That username has already been taken. Please choose a new username'})
        else:
            return render(request, 'accounts/registration.html', {'form': UserCreationForm(), 'error': 'Passwords did not match'})


def home_view(request):
    return render(request, 'home.html')

todo/views.py
from django.shortcuts import render, redirect
from .models import TodoModel
from .forms import TodoForm
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView, RedirectView
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class TodoCreate(LoginRequiredMixin, CreateView):
    model = TodoModel
    form_class = TodoForm
    template_name = 'todo/create_update.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect(self.get_success_url())


class TodoList(LoginRequiredMixin, ListView):
    model = TodoModel
    template_name = 'todo/list.html'
    context_object_name = 'todo_list'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(completed__isnull=True, user=self.request.user).order_by('created')


class TodoDetail(LoginRequiredMixin, DetailView):
    model = TodoModel
    template_name = 'todo/detail.html'
    context_object_name = 'todo'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

class TodoComplete(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        todo_obj = get_object_or_404(TodoModel, user=self.request.user, pk=kwargs['pk'])
        if todo_obj:
            todo_obj.completed=timezone.now()
            todo_obj.save()
        return reverse_lazy('todo:list')



class TodoEdit(LoginRequiredMixin, UpdateView):
    model = TodoModel
    template_name = 'todo/create_update.html'
    form_class = TodoForm

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class TodoDelete(LoginRequiredMixin, DeleteView):
    model = TodoModel
    template_name = 'todo/deleted.html'
    success_url = reverse_lazy('todo:list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)
    


class TodoCompletedList(LoginRequiredMixin, ListView):
    model = TodoModel
    template_name = 'todo/complete_list.html'
    context_object_name = 'todo_complete_list'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(completed__isnull=False, user=self.request.user).order_by('completed')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>
    <form method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login">
    </form>
{% endblock content %}

accounts/templates/accounts/registration.html
  
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                {% comment %} Do you already have an account? <a href="{% url 'loginuser' %}">Login here</a> {% endcomment %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Done-Dana-Done-Done</title>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script></head>
<body>
    <div class="container">
        <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href={% url 'home' %}>
                <img src="{% static 'project/logo.png' %}" width="50" height="50" alt="">Home
            </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto navbar-right">
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:create' %}">Create Todo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:list' %}">List Todos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:complete_list' %}">Completed Todos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% endif %}
                </ul>
            </div>
        </nav>
    
        <!-- <div class="container">
            <div class="row"> -->
        
            {%block content%}
            {%endblock%}
</div>
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
   <h1>Welcome to Done-Dana-Done-Done</h1>
{% endblock content %}

todo/templates/todo/complete_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Completed List of Todos</h1>
{% for todo in todo_complete_list %}
<h3><a href="{% url 'todo:detail' pk=todo.pk %}">{{todo.title}}</a></h3>
<h4>{{todo.memo}}</h4>
<p>
    <b>Created on {{todo.created}}</b><br>
<b>Completed on {{todo.completed}}</b><br>
</p>
{% endfor %}
{% endblock content %}

todo/templates/todo/create_update.html
{% extends 'base.html' %}
{% block content %}
{%if not form.instance.pk %}
<h1>Create New Todo</h1>
{% else %}
<h1>Update Todo</h1>
{% endif %}
<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

todo/templates/todo/deleted.html
{% extends 'base.html' %}
{% block content %}
<h3>Are you sure you want to delete?</h3>
<form method='POST'>
{%csrf_token%}
<input type="submit" class='btn btn-danger' value="Delete">
<a href="{% url 'todo:list' %}" class='btn btn-primary'>Cancel</a>
</form>
{% endblock content %}

todo/templates/todo/detail.html
{% extends 'base.html' %}
{% block content %}
<h1></h1>
<h1>{{todo.title}}</h3>
<p>{{todo.memo}}</p>
<p>
<b>{{todo.created}}</b><br></p>
<a href="{% url 'todo:edit' pk=todo.pk%}" class="btn btn-success">Edit</a>
<a href="{% url 'todo:delete' pk=todo.pk %}" class="btn btn-danger">Delete</a>
<a href="{% url 'todo:complete' pk=todo.pk %}" class="btn btn-warning">Complete</a>
{% endblock content %}

todo/templates/todo/list.html
{% extends 'base.html' %}
{% block content %}
<h1>List of Todos</h1>
{% for todo in todo_list %}
<h3><a href="{% url 'todo:detail' pk=todo.pk %}">{{todo.title}}</a></h3>
<h4>{{todo.memo}}</h4>
<p>
    <b>{{todo.created}}</b><br>
</p>
{% endfor %}
{% endblock content %}